import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Albatross",
  description:
    "Terms of Service for Albatross, the daily lateral thinking puzzle game.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <Link
        className="mb-10 inline-block text-muted-foreground text-sm transition-colors hover:text-foreground"
        href="/"
      >
        ← Back to game
      </Link>

      <h1 className="mb-2 text-4xl text-foreground">Terms of Service</h1>
      <p className="mb-10 text-muted-foreground text-sm">
        Last updated: March 30, 2026
      </p>

      <div className="space-y-8 text-foreground text-lg leading-relaxed">
        <section>
          <h2 className="mb-3 text-2xl text-foreground">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using Albatross ("the Service"), you agree to be
            bound by these Terms of Service. If you do not agree to these terms,
            please do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">
            2. Description of Service
          </h2>
          <p>
            Albatross is a daily lateral thinking puzzle game. Each day, a new
            puzzle is made available. Players ask yes-or-no questions, which are
            evaluated by an AI model, in an attempt to deduce the solution.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">3. Eligibility</h2>
          <p>
            You must be at least 13 years of age to use the Service. By using
            the Service, you represent that you meet this requirement. If you
            are under 18, you represent that a parent or guardian has reviewed
            and agreed to these Terms on your behalf.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">4. User Accounts</h2>
          <p>
            The Service may allow you to create an account to track your puzzle
            history. You are responsible for keeping your login credentials
            secure. You may not share your account or use another person's
            account. We reserve the right to suspend or terminate accounts that
            violate these Terms.
          </p>
          <p className="mt-3">
            You may also use the Service without creating an account. Anonymous
            sessions are created automatically to save your progress within a
            session.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="mt-3 list-inside list-disc space-y-2">
            <li>
              Use the Service for any unlawful purpose or in violation of any
              applicable law
            </li>
            <li>
              Submit questions or content that is abusive, harassing,
              threatening, defamatory, obscene, or otherwise objectionable
            </li>
            <li>
              Attempt to reverse-engineer, scrape, or automate interaction with
              the Service
            </li>
            <li>
              Interfere with or disrupt the integrity or performance of the
              Service
            </li>
            <li>
              Attempt to gain unauthorised access to any part of the Service or
              its infrastructure
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">
            6. AI-Generated Content
          </h2>
          <p>
            Responses to your questions are generated by an AI language model.
            These responses are provided for entertainment purposes only and may
            occasionally be inaccurate, inconsistent, or unexpected. We do not
            guarantee the accuracy of any AI-generated response. The AI's
            judgment on any given question is final within the game context.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">
            7. Intellectual Property
          </h2>
          <p>
            All puzzle content, branding, design, and software comprising the
            Service are owned by or licensed to Albatross and are protected by
            applicable intellectual property laws. You may not reproduce,
            distribute, or create derivative works from any part of the Service
            without our prior written consent.
          </p>
          <p className="mt-3">
            Questions you submit to the Service are not claimed as our property,
            but by submitting them you grant us a non-exclusive, royalty-free
            licence to use them for the purposes of operating and improving the
            Service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">8. Disclaimers</h2>
          <p>
            The Service is provided "as is" and "as available" without warranty
            of any kind, express or implied, including but not limited to
            warranties of merchantability, fitness for a particular purpose, or
            non-infringement. We do not warrant that the Service will be
            uninterrupted, error-free, or free of harmful components.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">
            9. Limitation of Liability
          </h2>
          <p>
            To the fullest extent permitted by law, Albatross and its operators
            shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages arising from your use of or
            inability to use the Service, even if advised of the possibility of
            such damages. Our total liability to you for any claim arising from
            these Terms or the Service shall not exceed the amount you paid us
            in the twelve months preceding the claim (which, for a free service,
            is zero).
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">
            10. Third-Party Services
          </h2>
          <p>
            The Service relies on third-party infrastructure including Supabase
            (database and authentication), Vercel (hosting and analytics), and
            AI model providers. Your use of the Service is also subject to the
            terms and privacy policies of these providers. We are not
            responsible for the practices of any third-party services.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">
            11. Modifications to the Service and Terms
          </h2>
          <p>
            We reserve the right to modify or discontinue the Service at any
            time without notice. We may also update these Terms from time to
            time. The "last updated" date at the top of this page reflects the
            most recent revision. Continued use of the Service after changes are
            posted constitutes your acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">12. Governing Law</h2>
          <p>
            These Terms are governed by and construed in accordance with
            applicable law, without regard to conflict-of-law principles. Any
            disputes arising from these Terms or the Service shall be resolved
            through good-faith negotiation in the first instance.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-2xl text-foreground">13. Contact</h2>
          <p>
            If you have questions about these Terms, please contact us at{" "}
            <a
              className="underline underline-offset-4"
              href="mailto:avchen4@gmail.com"
            >
              avchen4@gmail.com
            </a>
            .
          </p>
        </section>
      </div>

      <div className="mt-12 border-border border-t pt-8">
        <Link
          className="text-muted-foreground text-sm underline underline-offset-4 transition-colors hover:text-foreground"
          href="/privacy"
        >
          Read our Privacy Policy
        </Link>
      </div>
    </div>
  );
}
